export var camposEstaciones = [
  { id: 'ID_ESTACION', text: 'ID_ESTACION' },
  { id: 'ESTACION', text: 'ESTACION' },
  { id: 'CODIGO_ESTACION_EAAB', text: 'CODIGO_ESTACION_EAAB' },
  { id: 'CODIGO_ESTACION_IDEAM', text: 'CODIGO_ESTACION_IDEAM' },
  { id: 'ID_CATEGORIA', text: 'ID_CATEGORIA' },
  { id: 'CATEGORIA', text: 'CATEGORIA' },
  { id: 'TECNOLOGIA', text: 'TECNOLOGIA' },
  { id: 'ID_TECNOLOGIA', text: 'ID_TECNOLOGIA' },
  { id: 'TIPO_ESTACION', text: 'ID_TIPO_ESTACION' },
  { id: 'ID_TIPO_ESTACION', text: 'ID_TIPO_ESTACION' },
  { id: 'ENTIDAD', text: 'ENTIDAD' },
  { id: 'ID_ENTIDAD', text: 'ID_ENTIDAD' },
  { id: 'ID_ESTADO', text: 'ID_ESTADO' },
  { id: 'ESTADO', text: 'ESTADO' },
  { id: 'FECHA_INSTALACION', text: 'FECHA_INSTALACION' },
  { id: 'ALTITUD', text: 'ALTITUD' },
  { id: 'CORRIENTE', text: 'CORRIENTE' },
  { id: 'ID_CORRIENTE', text: 'ID_CORRIENTE' },
  { id: 'ZONA_OPERATIVA_EAAB', text: 'ZONA_OPERATIVA_EAAB' },
  { id: 'MUNICIPIO', text: 'MUNICIPIO' },
  { id: 'ID_MUNICIPIO', text: 'ID_MUNICIPIO' },
  { id: 'AREA_HIDROGRAFICA', text: 'AREA_HIDROGRAFICA' },
  { id: 'ZONA_HIDROGRAFICA', text: 'ZONA_HIDROGRAFICA' },
  { id: 'SUBZONA_HIDROGRAFICA', text: 'SUBZONA_HIDROGRAFICA' },
  { id: 'NIVEL_SUBSIGUIENTE', text: 'NIVEL_SUBSIGUIENTE' },
  { id: 'CUENCA', text: 'CUENCA' },
  { id: 'SUBCUENCA', text: 'SUBCUENCA' },
  { id: 'MICROCUENCA', text: 'MICROCUENCA' },
  { id: 'ID_TIPO_COORDENADAS', text: 'ID_TIPO_COORDENADAS' },
  { id: 'ACTIVO_ESTACION', text: 'ACTIVO_ESTACION' },
  { id: 'ESTACION_PRINCIPAL', text: 'ESTACION_PRINCIPAL' },
  { id: 'ID_AREA_HIDROGRAFICA', text: 'ID_AREA_HIDROGRAFICA' },
  { id: 'ID_ZONA_HIDROGRAFICA', text: 'ID_ZONA_HIDROGRAFICA' },
  { id: 'ID_SUBZONA_HIDROGRAFICA', text: 'ID_SUBZONA_HIDROGRAFICA' },
  { id: 'ID_CUENCA', text: 'ID_CUENCA' },
  { id: 'ID_SUBCUENCA', text: 'ID_SUBCUENCA' },
  { id: 'ID_MICROCUENCA', text: 'ID_MICROCUENCA' },
  { id: 'LATITUD', text: 'LATITUD' },
  { id: 'LONGITUD', text: 'LONGITUD' },
  { id: 'NORTE', text: 'NORTE' },
  { id: 'ESTE', text: 'ESTE' },
  { id: 'NUSLIM', text: 'NUSLIM' },
];

export var camposOBservaciones = [
  { id: 'ID_OBSERVACION_X_ESTACION_INICIAL' },
  { id: 'ID_PARAMETRO_X_ESTACION' },
  { id: 'FECHA' },
  { id: 'VALOR' },
  { id: 'FECHA_CARGUE' },
  { id: 'USUARIO_CARGUE' },
  { id: 'ORIGEN_OBSERVACION' },
  { id: 'ID_TIPO_ORIGEN_OBSERVACION' },
  { id: 'ORIGEN' },
  { id: 'ESTADO_OBSERVACION' },
  { id: 'ID_ESTADO_OBSERVACION' },
  { id: 'ID_FLAG_OBSERVACION' },
  { id: 'FLAG_OBSERVACION' },
  { id: 'ACTIVO_OBSERVACION' },
  { id: 'FECHA_CREACION' },
  { id: 'FECHA_MODIFICACION' },
  { id: 'FECHA_ESTADO' },
  { id: 'USUARIO_CREACION' },
  { id: 'USUARIO_MODIFICACION' },
  { id: 'USUARIO_ESTADO' },
  { id: 'FLAG_MIGRACION' },
];

export var camposParametros = [
  { id: 'ID_PARAMETRO' },
  { id: 'ID_VARIABLE' },
  { id: 'CODIGO' },
  { id: 'DESCRIPCION' },
  { id: 'ID_UNIDAD_MEDIDA' },
  { id: 'UNIDAD_MEDIDA' },
  { id: 'ID_TIPO_PARAMETRO' },
  { id: 'TIPO_PARAMETRO' },
  { id: 'ID_METODO' },
  { id: 'METODO' },
  { id: 'ID_PERIODO' },
  { id: 'PERIODO' },
  { id: 'ACTIVO_PARAMETRO' },
];

export var camposEmbalses = [
  { id: 'ID_EMBALSE' },
  { id: 'EMBALSE' },
  { id: 'ID_ENTIDAD' },
  { id: 'ENTIDAD' },
  { id: 'ZONA_OPERATIVA_EAAB' },
  { id: 'FECHA_INICIO_OPERACION' },
  { id: 'ELEVACION' },
  { id: 'VOLUMEN_TOTAL' },
  { id: 'VOLUMEN_UTIL' },
  { id: 'VOLUMEN_MUERTO' },
  { id: 'LONGITUD_CRESTA' },
  { id: 'ANCHO_CRESTA' },
  { id: 'ID_MUNICIPIO' },
  { id: 'MUNICIPIO' },
  { id: 'AREA_HIDROGRAFICA' },
  { id: 'ZONA_HIDROGRAFICA' },
  { id: 'SUBZONA_HIDROGRAFICA' },
  { id: 'NIVEL_SUBSIGUIENTE' },
  { id: 'CUENCA' },
  { id: 'SUBCUENCA' },
  { id: 'MICROCUENCA' },
  { id: 'ALTURA_PRESA' },
  { id: 'ACTIVO_EMBALSE' },
  { id: 'ID_AREA_HIDROGRAFICA' },
  { id: 'ID_ZONA_HIDROGRAFICA' },
  { id: 'ID_SUBZONA_HIDROGRAFICA' },
  { id: 'ID_CUENCA' },
  { id: 'ID_SUBCUENCA' },
  { id: 'ID_MICROCUENCA' },
];

export var camposPozos = [
  { id: 'ID_POZO' },
  { id: 'POZO' },
  { id: 'ZONA_OPERATIVA_EAAB' },
  { id: 'FECHA_INICIO_OPERACION' },
  { id: 'COTA_BOCA' },
  { id: 'COTA_MEDIDOR' },
  { id: 'PROFUNDIDAD' },
  { id: 'ID_TIPO_POZO' },
  { id: 'TIPO_POZO' },
  { id: 'ID_CATEGORIA' },
  { id: 'CATEGORIA' },
  { id: 'ID_CONDICION' },
  { id: 'CONDICION' },
  { id: 'ID_MUNICIPIO' },
  { id: 'MUNICIPIO' },
  { id: 'AREA_HIDROGRAFICA' },
  { id: 'ZONA_HIDROGRAFICA' },
  { id: 'SUBZONA_HIDROGRAFICA' },
  { id: 'NIVEL_SUBSIGUIENTE' },
  { id: 'CUENCA' },
  { id: 'SUBCUENCA' },
  { id: 'MICROCUENCA' },
  { id: 'ID_TIPO_COORDENADAS' },
  { id: 'TIPO_COORDENADAS' },
  { id: 'ACTIVO_POZO' },
  { id: 'ID_AREA_HIDROGRAFICA' },
  { id: 'ID_ZONA_HIDROGRAFICA' },
  { id: 'ID_SUBZONA_HIDROGRAFICA' },
  { id: 'ID_CUENCA' },
  { id: 'ID_SUBCUENCA' },
  { id: 'ID_MICROCUENCA' },
  { id: 'LATITUD' },
  { id: 'LONGITUD' },
  { id: 'NORTE' },
  { id: 'ESTE' },
];
