export interface  IEstacion{ 
   idEstacion: number,
   activo: string,
   altitud: number,
   areaHidrografica: string,
   estacion: string,
   codigoEstacionEaab: string,
   codigoEstacionIdeam: string,
   corriente: string,
   cuenca: string,
   este: number,
   fechaCreacion: string,
   fechaInstalacion: string,
   fechaModificacion: string,
   idCategoria: number,
   idEntidad: number,
   idEstado: number,
   idMunicipio: number,
   idTecnologia: number,
   idTipoCoordenadas: number,
   idTipoEstacion: number,
   latitud: number,
   microCuenca: string,
   nivelSubSiguiente: string,
   norte: number,
   subZonaHidrografica: string,
   usuarioCreacion:string,
   usuarioEstado:string,
   usuarioModificacion:string,
   zonaHidrografica: string,
   zonaOperativaEaab: string
}

export interface IEstacionDTO{ 
   activo: string,
   altitud: number,
   areaHidrografica: string,
   categoria: string,
   codigoEstacionEaab: string,
   codigoEstacionIdeam: string,
   corriente: string,
   cuenca: string,
   departamento: string,
   entidad: string,
   estacion: string,
   estado: string,
   este: number,
   fechaCreacion: number,
   fechaEstado: number,
   fechaInstalacion: number,
   fechaModificacion: number,
   idAreaHidrografica: string,
   idCategoria: number,
   idCorriente: number,
   idCuenca: string,
   idDepartamento: number,
   idEntidad: number,
   idEstacion: number,
   idEstado: number,
   idMicroCuenca: string,
   idMunicipio: number,
   idSubCuenca: string,
   idSubZonaHidrografica: string,
   idTecnologia: number,
   idTipoCoordenadas: number,
   idTipoEstacion: number,
   idZonaHidrografica: string,
   latitud: number,
   longitud: number,
   microCuenca: string,
   municipio: string,
   nivelSubSiguiente: string,
   norte: number,
   subCuenca: string,
   subZonaHidrografica: string,
   tecnologia: string,
   tipoCoordenadas: string,
   tipoEstacion: string,
   usuarioCreacion: string,
   usuarioEstado: string,
   usuarioModificacion: string,
   zonaHidrografica: string,
   zonaOperativaEaab: string
}

export interface IParametrosEstaciones{
   idParametroXEstacion:number,
   idParametro:number,
   idEstacion:number ,
   
}

export interface IFiltrosEstacion {
   codigoParametros : number[], 
}

export interface IParametrosCFrecuencias {
   idEstacion : number, 
   idPeriodos : number[], 
}
